name: Test
on: [push, pull_request]

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.1
          bundler-cache: true
          cache-version: gems-${{ hashFiles('Gemfile') }}
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "10"
      - name: Setup application
        env:
          RAILS_ENV: test
        run: |
          bundle exec rake db:create db:migrate
      - name: Run tests
        run: bundle exec rspec
